### ISSUE TITLE
android 10 not connect

### ISSUE THREAD

**Issue by KinG-InFeT** [sushichop/cordova-plugin-wifi-manager#18]
Hi,
i tested on my samsung tab s6 lite with android 10, the plugin return onUnavailable , not connect to wifi.

i'm here for any possible test

**Comment by sushichop** [comment]
@KinG-InFeT 
Thanks for reporting this and sorry for late response.
I confirmed bug with `cordova-plugin-wifi-manager@0.3.0`.

Can you try use `cordova-plugin-wifi-manager@0.2.1` instead?
I confirmed this version works fine with Android 10 again(yesterday).

Thanks

**Comment by sushichop** [comment]
I have released cordova-plugin-wifi-manager@0.4.1 which fixes a few things and has some changes. 

Thanks.
